openapi: 3.1.0
info:
  title: U-dummy
  description: API spec U-dummy , U-dummy is cloning of udemy
  version: 1.0.0
  contact:
    name: Naufela Rashif
    email: naufelarashif@gmail.com
servers:
  - url: https://localhost:3000/api
    description: Development Server
externalDocs :
  - url : https://www.udemy.com/
    description: udemy website
paths:
  /cart:
    get:
    post:
    delete:
  /cart{usersId}:
    get:
  /categories :
    get:
    put:
    post:
    delete:
  /courses:
    get:
      summary: Get All courses
    post:
      summary: Create new courses
      requestBody:
        content:
          application/json:
            schema:
              type:
                - object
              properties:
                type
    Head:
  /courses/{courseId} :
    get:
      summary: Get Courses
      description:
      parameters:
        - name: courseId
          in: path
          required: true
          description: required CoursesId for Get course
          schema:


    put:
      summary: Updates Courses
      description:
      parameters:
        - name: courseId
          in: path
          required: true
          description: required CoursesId for course updates
          schema:
              type: string
              pattern: "^[0-9]{1,16}$"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
      responses:


    delete:
      summary: Delete Courses
      description:
      parameters:
        - name: courseId
          in: path
          required: true
          description: required CoursesId for course updates
      responses:

    Head:

  /users:
    get:
      summary:
    post:
      summary: Register User
  /users/login:
    post:
      summary: Login User
  /users/current:
    get:
      summary: Get User
    delete:
      summary: Logout User
    patch:
      summary: Update User
  /contacts:
    get:
      summary: Search Contact
    post:
      summary: Create Contact
  /contacts/{contactsId}:
    get:
      summary: Get Contact
    put:
      summary: Update Contact
    delete:
      summary: Remove Contact
  /contacts/{contactsId}/addresses:
    get:
     summary: List Address
    post:
      summary: Create Address
  /contacts/{contactsId}/addresses/{addressesId}:
    get:
      summary: Get Address
    put:
      summary: Update Address
    delete:
      summary: Remove Address









components:
  securitySchemes:
    CategoryAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: Authentication for Category API
  schemas:
    CreateOrUpdateCategory:
      type: object
      properties:
        name:
          type: string
    Category:
      type: object
      properties:
        id:
          type: number
        name:
          type: string
